#!/usr/bin/env python3
"""Turn the CUB-200 experiment JSONs (E1/E2/E3) into the paper's figures, tables,
and macros. Chance-corrected ARI is the headline metric (NMI is inflated at fine
ranks). Reads every data/experiments_out/cub_experiments_*.json except *smoke*, in name order;
a later file replaces earlier E1/E2/E3 blocks, so a fresh step-2 run (cub_experiments_real.json)
supersedes the bundled e1e3/e2 results. Figure 1 uses the printed figure's 3.35 x 2.15 in canvas.
NO hand-typed numbers: everything derives from the JSONs.
"""
import glob, json, os
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

import sys as _sys; from pathlib import Path as _P
_sys.path.insert(0, str(_P(__file__).resolve().parent))
from common import DATA as _DATA, FIGURES as _FIG, EXPERIMENTS_OUT as _OUT
HERE = str(_DATA.parent)
OUT = str(_OUT)
FIG = str(_FIG)
os.makedirs(FIG, exist_ok=True)
RANKS = ["order", "family", "genus", "species"]
LAB = {"order": "Order", "family": "Family", "genus": "Genus", "species": "Species"}
# Okabe-Ito, CVD-validated (dE 37); relief = distinct markers + direct labels
COL = {"order": "#0072B2", "family": "#E69F00", "genus": "#009E73", "species": "#D55E00"}
INK, MUT = "#1a1a1a", "#6b6b6b"

plt.rcParams.update({"pdf.fonttype": 42, "ps.fonttype": 42, "font.family": "serif",
                     "font.size": 8, "axes.edgecolor": "#bdbdbd", "axes.linewidth": 0.6,
                     "xtick.color": INK, "ytick.color": INK, "text.color": INK})


def load():
    d = {}
    for f in sorted(glob.glob(os.path.join(OUT, "cub_experiments_*.json"))):
        if any(w in os.path.basename(f) for w in ("smoke", "control", "subsample")):
            continue                                # only full runs on the real embeddings
        j = json.load(open(f, encoding="utf-8"))
        for k in ("E1_divisive", "E2_ablation", "E3_pca_sweep"):
            if k in j:
                d[k] = j[k]
        d.setdefault("oracle_k", j.get("oracle_k"))
        d.setdefault("seeds", j.get("seeds"))
    return d


def fig_pca_sweep(e3):
    dims = e3["dims"]
    fig, ax = plt.subplots(figsize=(3.35, 2.15))
    for r in RANKS:
        y = [e3["per_rank"][r][str(dd)]["ari"]["mean"] for dd in dims]
        ax.plot(dims, y, color=COL[r], marker="o", ms=4, lw=1.8, clip_on=False, zorder=3)
        ax.annotate(LAB[r], (dims[-1], y[-1]), xytext=(4, 0), textcoords="offset points",
                    color=COL[r], fontsize=7.5, fontweight="bold", va="center")
    ax.axhline(0, color=MUT, lw=0.6, ls=":", zorder=1)
    ax.set_xscale("log", base=2)
    ax.set_xticks(dims)
    # label every other dimension, anchored to the endpoint so the max always shows
    ax.set_xticklabels([str(x) if (len(dims) - 1 - i) % 2 == 0 else "" for i, x in enumerate(dims)], fontsize=7)
    ax.set_xlabel("PCA dimensionality (log$_2$)")
    ax.set_ylabel("ARI (chance-corrected)")
    ax.set_xlim(dims[0], dims[-1] * 2.0)
    ax.grid(axis="y", color="#e8e8e8", lw=0.6, zorder=0)
    for s in ("top", "right"):
        ax.spines[s].set_visible(False)
    fig.tight_layout(pad=0.3)
    for ext in ("pdf", "png"):                                 # dual-format, as for fig_simmatrix
        out = os.path.join(FIG, f"fig_pca_sweep.{ext}")
        fig.savefig(out, bbox_inches="tight", pad_inches=0.02, dpi=300,
                    metadata={"CreationDate": None} if ext == "pdf" else None)   # no timestamp: reruns match
        print("wrote", out)


def macros(d):
    m = ["% auto-generated by reprocub/fig_sweep_table.py (via 04_make_figures.py) -- no hand-typed numbers"]

    def nf(x, p=3):
        return f"{x:.{p}f}"

    # E3: per fine rank, peak ARI and the dim that achieves it (saturation)
    if "E3_pca_sweep" in d:
        e3 = d["E3_pca_sweep"]; dims = e3["dims"]
        for r in RANKS:
            ys = {dd: e3["per_rank"][r][str(dd)]["ari"]["mean"] for dd in dims}
            peak = max(ys, key=ys.get)
            m.append(f"\\newcommand{{\\Sweep{LAB[r]}Peak}}{{{nf(ys[peak])}}}")
            m.append(f"\\newcommand{{\\Sweep{LAB[r]}PeakDim}}{{{peak}}}")
            m.append(f"\\newcommand{{\\Sweep{LAB[r]}Full}}{{{nf(ys[dims[-1]])}}}")   # ARI at 4096
        m.append(f"\\newcommand{{\\SweepDimMax}}{{{dims[-1]}}}")
    # E1: flat vs divisive ARI per rank
    if "E1_divisive" in d:
        e1 = d["E1_divisive"]
        for r in RANKS:
            f, dv = e1[r]["flat_kmeans"], e1[r]["divisive_bisecting"]
            m.append(f"\\newcommand{{\\Flat{LAB[r]}ARI}}{{{nf(f['ari']['mean'])}}}")
            m.append(f"\\newcommand{{\\Flat{LAB[r]}NMI}}{{{nf(f['nmi']['mean'])}}}")
            m.append(f"\\newcommand{{\\Div{LAB[r]}ARI}}{{{nf(dv['ari']['mean'])}}}")
    # E2: best method per rank (by ARI) + whether Order ever clears a threshold
    if "E2_ablation" in d:
        e2 = d["E2_ablation"]
        for r in RANKS:
            vals = {mth: e2[mth][r]["ari"]["mean"] for mth in e2 if "ari" in e2[mth].get(r, {})}
            if vals:
                best = max(vals, key=vals.get)
                m.append(f"\\newcommand{{\\Best{LAB[r]}Method}}{{{best.replace('_','-')}}}")
                m.append(f"\\newcommand{{\\Best{LAB[r]}ARI}}{{{nf(vals[best])}}}")
        so = e2.get("spectral", {}).get("order", {})
        if "ari" in so:
            m.append(f"\\newcommand{{\\OrderStdSpectral}}{{{nf(so['ari']['std'], 2)}}}")
    # class imbalance: majority-order fraction from the label file
    lp = str(_DATA / "cub200_labels.json")
    if os.path.exists(lp):
        from collections import Counter
        ol = json.load(open(lp, encoding="utf-8"))["labels"]["order"]
        m.append(f"\\newcommand{{\\MajorityOrderPct}}{{{round(Counter(ol).most_common(1)[0][1] / len(ol) * 100)}}}")
    print("\n=== result macros (compare with data/paper_macros.tex) ===")
    print("\n".join(m))
    return m                                   # returned so tests can diff them against the .tex


def table_ablation(e2):
    """ARI per method per rank -- shows whether any method rescues Order."""
    order = ["kmeans", "kmeans_whiten", "bisecting", "ward", "gmm_diag", "spectral"]
    disp = {"kmeans": "$k$-means", "kmeans_whiten": "$k$-means (standardised)",
            "bisecting": "Bisecting (divisive)", "ward": "Ward", "gmm_diag": "GMM",
            "spectral": "Spectral"}
    colmax = {r: max(e2[m][r]["ari"]["mean"] for m in order if m in e2 and "ari" in e2[m].get(r, {}))
              for r in RANKS}
    rows = ["% auto-generated -- ARI (chance-corrected), mean over seeds; best per column in bold",
            "\\begin{tabular}{lcccc}", "\\hline",
            "\\textbf{Method} & \\textbf{Order} & \\textbf{Family} & \\textbf{Genus} & \\textbf{Species} \\\\",
            "\\hline"]
    for mth in order:
        if mth not in e2:
            continue
        cells = []
        for r in RANKS:
            v = e2[mth].get(r, {})
            if "ari" in v:
                s = f"{v['ari']['mean']:.3f}"
                # bold the column-best, but not the near-chance Order column (a bold there
                # would read as a "win" for a non-result)
                bold = abs(v["ari"]["mean"] - colmax[r]) < 1e-9 and r != "order"
                cells.append(f"\\textbf{{{s}}}" if bold else s)
            else:
                cells.append("--")
        rows.append(f"{disp[mth]} & " + " & ".join(cells) + " \\\\")
    rows += ["\\hline", "\\end{tabular}"]
    print("\n=== Table 1 of the paper (ARI) ===")
    print("\n".join(rows))


if __name__ == "__main__":
    d = load()
    print("loaded:", [k for k in ("E1_divisive", "E2_ablation", "E3_pca_sweep") if k in d])
    if "E3_pca_sweep" in d:
        fig_pca_sweep(d["E3_pca_sweep"])
    if "E2_ablation" in d:
        table_ablation(d["E2_ablation"])
    macros(d)